api_platform:
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
    html: ['text/html']

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  title: 'TrelloLike API'
  version: '1.0.0'